# For help and tutorials, visit https://circleci.com/docs/
# For internal documentation visit https://enturas.atlassian.net/wiki/spaces/ESP/pages/580026490/CircleCI
version: 2.1

orbs:
#  slack: circleci/slack@1.0.0
  docker: circleci/docker@0.5.20
  node: circleci/node@1.1.6

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    executor:
      name: node/default
      tag: '10.13'
    steps:
      - *attach_workspace
      - checkout
      - node/with-cache:
          cache-key: yarn.lock
          cache-version: v1
          steps:
            - run: yarn
      - run:
          name: "Run tests"
          command: yarn test
      - run:
          name: "Create production build"
          command: yarn build
      - run:
          name: "Persist built files"
          command: |
            set -exu
            mv build /tmp/workspace/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build/*
  docker:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - *attach_workspace
      - run: |
          mv /tmp/workspace/build .
      - restore_cache:
          keys:
          - node-deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - docker/publish:
          digest-path: /tmp/digest.txt
          image: $CIRCLE_PROJECT_REPONAME
          tag: ${CIRCLE_BRANCH#"env/"}-v$CIRCLE_BUILD_NUM
          registry: $DOCKER_REGISTRY
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  "Build Pipeline":
    jobs:
      - build
      - docker:
          context: global
          filters:
            branches:
              only: v2
          requires:
            - build
