# For help and tutorials, visit https://circleci.com/docs/
# For internal documentation visit https://enturas.atlassian.net/wiki/spaces/ESP/pages/580026490/CircleCI
version: 2.1

orbs:
#  slack: circleci/slack@1.0.0
  docker: circleci/docker-publish@0.1.6
  node: circleci/node@1.1.6

jobs:
  install:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          cache-key: yarn.lock
          steps:
            - run: yarn
  test:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          cache-key: yarn.lock
          steps:
            - run: yarn test

  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          cache-key: yarn.lock
          steps:
            - run: yarn build

workflows:
  "Build Pipeline":
    jobs:
      - install
      - test:
        requires:
          - install
      - build:
        requires:
          - install
      - docker/publish: # TODO: attach workspace
          name: publish
          registry: $DOCKER_REGISTRY
          image: $CIRCLE_PROJECT_REPONAME
          tag: ${CIRCLE_BRANCH#"env/"}-v$CIRCLE_BUILD_NUM
          deploy: true
          context: global
          filters:
            branches:
              only: v2
          requires:
            - test
            - build
