apiVersion: v1
data:
  config.json: |
    {{ .Values.config }}

kind: ConfigMap
metadata:
  name: shamash-server-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
